apiVersion: v2
name: order-service
description: ScaleCart Order Service Helm chart
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../common"
