sonar.projectKey=scalecart_notification-service
sonar.organization=vaibhavyadav-cloud
sonar.sources=app
sonar.tests=app
sonar.test.inclusions=**/test_*.py,**/*_test.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8