sonar.projectKey=scalecart_frontend
sonar.organization=vaibhavyadav-cloud
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.tsx,**/*.test.ts
sonar.exclusions=**/*.test.tsx,**/*.test.ts,**/.next/**,**/out/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8