name: CI - notification-service

on:
  push:
    branches: [main]
    paths: ["services/notification-service/**"]
  pull_request:
    paths: ["services/notification-service/**"]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-scan-push.yml
    with:
      service_name: notification-service
      service_path: services/notification-service
      language: python
    secrets: inherit
